// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'AboutUs': typeof import("../components/AboutUs.vue")['default'],
    'Chart': typeof import("../components/Chart.vue")['default'],
    'FilterMenu': typeof import("../components/FilterMenu.vue")['default'],
    'Header': typeof import("../components/Header.vue")['default'],
    'Roadmap': typeof import("../components/Roadmap.vue")['default'],
    'IconsHero': typeof import("../components/icons/hero.vue")['default'],
    'IconsLogo': typeof import("../components/icons/logo.vue")['default'],
    'IconsMetamask': typeof import("../components/icons/metamask.vue")['default'],
    'IconsPeople': typeof import("../components/icons/people.vue")['default'],
    'IconsRocket': typeof import("../components/icons/rocket.vue")['default'],
    'UiButton': typeof import("../components/ui/Button.vue")['default'],
    'UiContainer': typeof import("../components/ui/Container.vue")['default'],
    'UiIcon': typeof import("../components/ui/Icon.vue")['default'],
    'UiSlider': typeof import("../components/ui/Slider.vue")['default'],
    'UiTable': typeof import("../components/ui/Table.vue")['default'],
    'UiTypography': typeof import("../components/ui/Typography.vue")['default'],
    'UiCardTitle': typeof import("../components/ui/Card/CardTitle.vue")['default'],
    'UiCard': typeof import("../components/ui/Card/index.vue")['default'],
    'UiGridCol': typeof import("../components/ui/Grid/Col.vue")['default'],
    'UiGridRow': typeof import("../components/ui/Grid/Row.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyAboutUs': typeof import("../components/AboutUs.vue")['default'],
    'LazyChart': typeof import("../components/Chart.vue")['default'],
    'LazyFilterMenu': typeof import("../components/FilterMenu.vue")['default'],
    'LazyHeader': typeof import("../components/Header.vue")['default'],
    'LazyRoadmap': typeof import("../components/Roadmap.vue")['default'],
    'LazyIconsHero': typeof import("../components/icons/hero.vue")['default'],
    'LazyIconsLogo': typeof import("../components/icons/logo.vue")['default'],
    'LazyIconsMetamask': typeof import("../components/icons/metamask.vue")['default'],
    'LazyIconsPeople': typeof import("../components/icons/people.vue")['default'],
    'LazyIconsRocket': typeof import("../components/icons/rocket.vue")['default'],
    'LazyUiButton': typeof import("../components/ui/Button.vue")['default'],
    'LazyUiContainer': typeof import("../components/ui/Container.vue")['default'],
    'LazyUiIcon': typeof import("../components/ui/Icon.vue")['default'],
    'LazyUiSlider': typeof import("../components/ui/Slider.vue")['default'],
    'LazyUiTable': typeof import("../components/ui/Table.vue")['default'],
    'LazyUiTypography': typeof import("../components/ui/Typography.vue")['default'],
    'LazyUiCardTitle': typeof import("../components/ui/Card/CardTitle.vue")['default'],
    'LazyUiCard': typeof import("../components/ui/Card/index.vue")['default'],
    'LazyUiGridCol': typeof import("../components/ui/Grid/Col.vue")['default'],
    'LazyUiGridRow': typeof import("../components/ui/Grid/Row.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  }
}
export const AboutUs: typeof import("../components/AboutUs.vue")['default']
export const Chart: typeof import("../components/Chart.vue")['default']
export const FilterMenu: typeof import("../components/FilterMenu.vue")['default']
export const Header: typeof import("../components/Header.vue")['default']
export const Roadmap: typeof import("../components/Roadmap.vue")['default']
export const IconsHero: typeof import("../components/icons/hero.vue")['default']
export const IconsLogo: typeof import("../components/icons/logo.vue")['default']
export const IconsMetamask: typeof import("../components/icons/metamask.vue")['default']
export const IconsPeople: typeof import("../components/icons/people.vue")['default']
export const IconsRocket: typeof import("../components/icons/rocket.vue")['default']
export const UiButton: typeof import("../components/ui/Button.vue")['default']
export const UiContainer: typeof import("../components/ui/Container.vue")['default']
export const UiIcon: typeof import("../components/ui/Icon.vue")['default']
export const UiSlider: typeof import("../components/ui/Slider.vue")['default']
export const UiTable: typeof import("../components/ui/Table.vue")['default']
export const UiTypography: typeof import("../components/ui/Typography.vue")['default']
export const UiCardTitle: typeof import("../components/ui/Card/CardTitle.vue")['default']
export const UiCard: typeof import("../components/ui/Card/index.vue")['default']
export const UiGridCol: typeof import("../components/ui/Grid/Col.vue")['default']
export const UiGridRow: typeof import("../components/ui/Grid/Row.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyAboutUs: typeof import("../components/AboutUs.vue")['default']
export const LazyChart: typeof import("../components/Chart.vue")['default']
export const LazyFilterMenu: typeof import("../components/FilterMenu.vue")['default']
export const LazyHeader: typeof import("../components/Header.vue")['default']
export const LazyRoadmap: typeof import("../components/Roadmap.vue")['default']
export const LazyIconsHero: typeof import("../components/icons/hero.vue")['default']
export const LazyIconsLogo: typeof import("../components/icons/logo.vue")['default']
export const LazyIconsMetamask: typeof import("../components/icons/metamask.vue")['default']
export const LazyIconsPeople: typeof import("../components/icons/people.vue")['default']
export const LazyIconsRocket: typeof import("../components/icons/rocket.vue")['default']
export const LazyUiButton: typeof import("../components/ui/Button.vue")['default']
export const LazyUiContainer: typeof import("../components/ui/Container.vue")['default']
export const LazyUiIcon: typeof import("../components/ui/Icon.vue")['default']
export const LazyUiSlider: typeof import("../components/ui/Slider.vue")['default']
export const LazyUiTable: typeof import("../components/ui/Table.vue")['default']
export const LazyUiTypography: typeof import("../components/ui/Typography.vue")['default']
export const LazyUiCardTitle: typeof import("../components/ui/Card/CardTitle.vue")['default']
export const LazyUiCard: typeof import("../components/ui/Card/index.vue")['default']
export const LazyUiGridCol: typeof import("../components/ui/Grid/Col.vue")['default']
export const LazyUiGridRow: typeof import("../components/ui/Grid/Row.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const componentNames: string[]
